# Generated by Django 5.1.2 on 2025-02-18 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='school',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Practical', 'Practical'), ('Theory', 'Theory')], default='Theory', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_years',
            field=models.IntegerField(choices=[(3, '3 Years'), (4, '4 Years'), (5, '5 Years')], default=4),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.room'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
